service: deployit001
provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: eu-west-1
package:
 exclude:
   - ./**
 include:
   - ./bin/**
functions:
  deployit_lex:
    handler: bin/deployit_lex
    events:
      - http:
          path: /
          method: get